-- MySQL Script generated by MySQL Workbench
-- 07/31/15 20:56:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema estudotellksdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema estudotellksdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estudotellksdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `estudotellksdb` ;

-- -----------------------------------------------------
-- Table `estudotellksdb`.`generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudotellksdb`.`generos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_genero` VARCHAR(45) NOT NULL,
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_alteracao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_exclusao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `excluido` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudotellksdb`.`editoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudotellksdb`.`editoras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_editora` VARCHAR(45) NOT NULL,
  `excluido` TINYINT(1) NULL DEFAULT 0,
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_alteracao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_exclusao` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudotellksdb`.`livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudotellksdb`.`livros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_livro` VARCHAR(45) NOT NULL,
  `editora` VARCHAR(45) NULL,
  `edicao` VARCHAR(45) NULL,
  `quantidade_exemplares` INT NULL,
  `excluido` TINYINT(1) NULL DEFAULT 0,
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_alteracao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_exclusao` DATETIME NULL,
  `generos_id` INT NOT NULL,
  `editoras_id` INT NOT NULL,
  PRIMARY KEY (`id`, `generos_id`, `editoras_id`),
  INDEX `fk_livros_generos1_idx` (`generos_id` ASC),
  INDEX `fk_livros_editoras1_idx` (`editoras_id` ASC),
  CONSTRAINT `fk_livros_generos1`
    FOREIGN KEY (`generos_id`)
    REFERENCES `estudotellksdb`.`generos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livros_editoras1`
    FOREIGN KEY (`editoras_id`)
    REFERENCES `estudotellksdb`.`editoras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudotellksdb`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudotellksdb`.`autores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_autor` VARCHAR(45) NOT NULL,
  `excluido` TINYINT(1) NULL DEFAULT 0,
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_alteracao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_exclusao` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudotellksdb`.`livros_autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudotellksdb`.`livros_autores` (
  `livros_id` INT NOT NULL,
  `autores_id` INT NOT NULL,
  PRIMARY KEY (`livros_id`, `autores_id`),
  INDEX `fk_livros_has_autores_autores1_idx` (`autores_id` ASC),
  INDEX `fk_livros_has_autores_livros_idx` (`livros_id` ASC),
  CONSTRAINT `fk_livros_has_autores_livros`
    FOREIGN KEY (`livros_id`)
    REFERENCES `estudotellksdb`.`livros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livros_has_autores_autores1`
    FOREIGN KEY (`autores_id`)
    REFERENCES `estudotellksdb`.`autores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Alteração da tabela `estudotellksdb`.`livros`
-- -----------------------------------------------------
ALTER TABLE `estudotellksdb`.`livros` 
DROP COLUMN `editora`;